### ISSUE TITLE
Widget _searchInput returns a future inside setstate

### ISSUE THREAD

**Issue by EsbenSoeltoft** [ketanchoyal/mapbox_search_flutter#2]
in file map_box_place_search_widget.dart line 170 it calls setState(() => _autocompletePlace(value));

_autocompletePlace is a async function so it complains during runtime that a Future is returned during setState.

**Comment by pMertDogan** [comment]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() callback argument returned a Future.
E/flutter (23377): The setState() method on _MapBoxPlaceSearchWidgetState#93213(ticker inactive) was called with a closure or method that returned a Future. Maybe it is marked as "async".
E/flutter (23377): Instead of performing asynchronous work inside a call to setState(), first execute the work (without updating the widget state), and then synchronously update the state inside a call to setState().
E/flutter (23377): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1151:9)
E/flutter (23377): #1      State.setState (package:flutter/src/widgets/framework.dart:1167:6)
E/flutter (23377): #2      _MapBoxPlaceSearchWidgetState._searchInput.<anonymous closure>.<anonymous closure> (package:mapbox_search_flutter/src/map_box_place_search_widget.dart:170:21)
E/flutter (23377): #3      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (23377): #4      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (23377): #5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (23377): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (23377): #7      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (23377): #8      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (23377): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (23377): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23377): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (23377): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (23377): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (23377): `

**Comment by ketanchoyal** [comment]
I'll look into it asap!
